### ISSUE TITLE
Footer Links

### ISSUE THREAD

**Issue by pdw207** [ResistanceCalendar/resistance-calendar-frontend#98]

**Comment by pfarnach** [comment]
@pdw207 can you add a description or some details to this issue?

**Comment by pdw207** [comment]
@devin I think we need a privacy policy and other urls to link to.

**Comment by pfarnach** [comment]
I think that's the wrong Devin. @InciteDemocracy can you put the link details here?

**Comment by InciteDemocracy** [comment]
PRIVACY POLICY

Your privacy is important. We strive to provide you with a safe and secure user experience. We do not collect information through cookies. Our mailing list is solely for the purpose of informing people about updates to this specific project. Any personal information you provide to the team of volunteers, who run Resistance Calendar is maintained and accessible only by us unless specifically stated otherwise. We use aggregate data to monitor website traffic and track user experience. No personally identifiable information is disclosed in this process; only general information in aggregate form. Non-specific, aggregate data is also used for the purposes of collecting general demographic information, measuring user interests, and analyzing the collective characteristics and behaviors of our visitors. The collection of this information allows us to appropriately change, update, and service the website in accordance to common trends. Any modifications to this policy will be posted in this space. We welcome any questions or comments you have.

**Comment by InciteDemocracy** [comment]
Footer Links: 

HOME -> www.resistancecalendar.org
ADD EVENTS - ?
FACEBOOK -> https://www.facebook.com/resistancecalendar
TWITTER -> https://twitter.com/ResistCalendar
PRIVACY STATEMENT - New page with text (see above)

**Comment by pfarnach** [comment]
Closed with https://github.com/ResistanceCalendar/resistance-calendar-frontend/pull/127
